### ISSUE TITLE
Setting up WSL for Deep Learning

### ISSUE THREAD

**Issue by rayanrsr** [AmineDjeghri/BetterWindowsUX#5]
https://docs.nvidia.com/cuda/wsl-user-guide/index.html
https://towardsdatascience.com/cuda-on-wsl2-for-deep-learning-first-impressions-and-benchmarks-3c0178754035

**Comment by AmineDjeghri** [comment]
added : https://github.com/AmineDjeghri/AwesomeWindows11#install-cuda-in-wsl-
