### ISSUE TITLE
Typos 

### ISSUE THREAD

**Issue by GhostlyScript** [AmineDjeghri/BetterWindowsUX#6]
In this item: https://github.com/AmineDjeghri/AwesomeWindows11/blob/master/cuda_pytorch_install.md I think there are typos:

1. You say "Create a env.yaml file with the content above" however the content is below not above.
2. You say "conda env update -n nmy-env -f conda-env-gpu.yml;conda activate my-env;" 
This seems to have several typos?  i. nmy-env, ii. Your previous file was called env.yaml iii. Your previous example called the environment py-env not my-env, you mention conda-env-gpu.yml here but that wasn't mentioned previously?

**Comment by AmineDjeghri** [comment]
@GhostlyScript  thanks ! i will correct that

**Comment by AmineDjeghri** [comment]
@GhostlyScript 
https://github.com/AmineDjeghri/AwesomeWindows11/blob/master/cuda_pytorch_install.md

i did some updates and included the requirements.txt

tell me if everything is good so i can close the issue

**Comment by GhostlyScript** [comment]
Looks great, thank you!  I was wondering about the GPU yaml so thank you for clarifying that too.
